apiVersion: skupper.io/v2alpha1
kind: Connector
metadata:
  name: west-backend
  namespace: west
spec:
  routingKey: west-backend
  port: 9092
  selector: app=getback
---
apiVersion: skupper.io/v2alpha1
kind: Connector
metadata:
  name: west-backend-http
  namespace: west
spec:
  routingKey: west-backend-http
  port: 9091
  selector: app=getback
