apiVersion: v1
kind: Service
metadata:
  name: getback-tls
  namespace: west
  labels:
    app: getback-tls
spec:
  selector:
    app: getback-tls
  ports:
  - name: https
    port: 9091
    targetPort: 9091
    protocol: TCP
  - name: tls-tcp
    port: 9092
    targetPort: 9092
    protocol: TCP
  - name: dashboard
    port: 9093
    targetPort: 9093
    protocol: TCP
  type: ClusterIP
